### ISSUE TITLE
Support using `regexp` instead of `wildcard` in the text type

### ISSUE THREAD

**Issue by sadasant** [smartprocure/contexture-elasticsearch#13]
Either we make a new type called `regexp` or we extend the text type to use regexp, but according to Marc, switching to regexp will reduce the resources needed to run the queries, and we'll get the same results.

On the cases that say we have to `useQueryString` in the text type, we can change the `map` that wraps every word in quotes to this map:

```js
const vRegex = v.value.toString()
  .replace(/[.?+*|{}\[\]()]/g, '\\$&')
  .split('')
  .map((ch: any) => ch.match(/[A-Za-z]/) ? `[${ch.toUpperCase()}${ch.toLowerCase()}]` : ch)
  .join('');
```

After that we can use `regexp` instead of `wildcard`, and switch to `.untouched` instead of using `lowercased` and that's probably it!

Let's talk about it whenever possible.

**Comment by lusid** [comment]
Additionally, instead of adding `*` to the beginning and ending depending on how we are searching, it would need to add `.*` instead, and you would do that AFTER you've done the vRegex modification to ensure it doesn't get escaped.

Just to give an idea of what this would do as an example, it would change this:

```{
  "wildcard": {
    "somefield.lowercased": "*New York?*"
  }
}```

to this:

```{
  "regexp": {
    "somefield.keyword": ".*[Nn][Ee][Ww] [Yy][Oo][Rr][Kk]\?.*"
  }
}```

This means we would be able to use the non-analyzed field we already have to do contains, starts with, ends with, and exact searches instead of needing special fields that are analyzed to fake a keyword-like field but with lowercased characters. In our case, `.lowercased` and `.exact` could be removed completely, which are currently tripling the size of our index since they exact on almost every string field.
